### PR TITLE
3.15.2-release

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Comment by llowinge** [comment]
All tests passed with https://github.com/openshift/release/pull/59772 . Thus merging.

**Comment by llowinge** [comment]
@jirisimek98 Do you agree with the change in README related to not upgrading `oc` client anymore (due to incompability with UBI8) ? Did you somehow investigate it (i saw your comment) ?

**Comment by jirisimek98** [comment]
> @jirisimek98 Do you agree with the change in README related to not upgrading `oc` client anymore (due to incompability with UBI8) ? Did you somehow investigate it (i saw your comment) ?

Yes, that makes most sense IMO. I don't remember what exdactly caused the versions mismatch (I think it was some C library version) but the only solution for it to work was to upgrade to UBI9, which probably doesn't make sense if we do rhel8 interop

**Review by jirisimek98 — APPROVED** [review]

**Comment by llowinge** [comment]
@jirisimek98 @tveskrna I've finished it in the preferred way.

Tests passed - https://github.com/openshift/release/pull/60010

**Comment by tveskrna** [comment]
reviewd, LGTM

**Pull request merged**
